### ISSUE TITLE
greeter-hide-users=true not respected anymore?

### ISSUE THREAD

**Issue by maxnet** [raspberrypi-ui/pi-greeter#4]
The piserver images set greeter-hide-users=true in /etc/lightdm/lightdm.conf for obvious security and  compliance reasons.
However that does not seem to work anymore.

https://github.com/raspberrypi/piserver/issues/39

**Comment by spl237** [comment]
I can't repeat this problem.

I've just tried on the most recent image with the pi-greeter update we pushed over the weekend; with auto login disabled and the only enabled lines in /etc/lightdm/lightdm.conf being "greeter-session=pi-greeter" and "greeter-hide-users=true", I don't get a user dropdown in the greeter; just a box in which to enter a user name, which is what I would expect to happen.

The only recent change I have made in the greeter was to only set the autologin-user entry to "pi" if it was not currently set, but that shouldn't affect this anyway, as you'd need to comment that line out to see the greeter in the first place.

Do you only see this under piserver itself, or can you see it on a standard image booting standalone from microSD? Could you please post your lightdm.conf so I can see if I can repeat this?

**Comment by spl237** [comment]
There have been no recent updates to lightdm pulled from Debian, and the only changes to pi-greeter recently have been a font update and the aforementioned change to setting the default autologin user - I don't think either of these can have caused the problem reported.

**Comment by maxnet** [comment]
Correction.
It does still respect that option.
As on a fresh installation with the latest image the issue does not appear.

However I do can reproduce the issue by installing last month's 2018-10-11 image, and then execute "apt-get upgrade" (using chroot "shell" button in piserver).
Seems one of the packages overwrites my modified /etc/lightdm/lightdm.conf with your stock version.
Packages should not be doing that.

**Comment by spl237** [comment]
Ah - ok, in that case I can guess what is happening; the pi-greeter setup is resetting the greeter-hide-users line in your config to false.

I'll modify the postinst on that so it does the same as for the autologin user and only sets it if it is currently unset.

**Comment by spl237** [comment]
Package now modified to only set autologin-user, greeter-session and greeter-hide-users if not currently set - will be pushed to apt in the next couple of days.
